// The course in English — the same eleven lessons, cards and answers as content.zh.ts (lessons.test.ts
// holds the three languages to that). Terms follow everyday English Skat usage — pagat.com and the
// English Wikipedia, the official ISPA wording where it is also the common one: declarer, defenders,
// forehand / middlehand / rearhand, trick, skat, matadors "with / without", card points. The German
// words every Skat table uses (Grand, Null, Hand, Schneider, Schwarz, Ouvert) stay German. Decisions
// and sources: .intentfold/tickets/SKATGO-1/terms.md.

import { cards } from '../cards'
import {
  countPointsDrill,
  gameValueDrill,
  legalDrill,
  matadorDrill,
  orderDrill,
  pickTrumpsDrill,
  settleDrill,
  trickWinnerDrill,
} from './drills'
import { gen, times } from './build'
import type { Lesson } from './types'

export const LESSONS_EN: Lesson[] = [
  {
    id: '1',
    title: 'Three players, 32 cards',
    promise: 'Know what Skat is about: who plays against whom, what for, and how you win.',
    emoji: '🃏',
    minutes: 3,
    steps: [
      {
        kind: 'teach',
        title: "Germany's national card game",
        body: [
          'Skat is a trick-taking game for three players, and in Germany almost everyone knows it. It uses only 32 cards and a deal takes ten minutes, yet it tests your counting, your memory and your nerve all at once.',
          'The special thing: every deal is **one player against two**. The one who goes it alone is the **declarer**; the other two team up for that deal as the **defenders**. Who is declarer next time? That is fought out again.',
        ],
        tip: 'The course has 11 lessons. Each one explains, then lets you practise, and the last one is a whole game against two computer opponents — after that you are ready for a real table.',
      },
      {
        kind: 'teach',
        title: '32 cards',
        body: ['Take an ordinary deck, remove the 2s to 6s and the jokers, and what is left is a Skat deck: four suits ♣ ♠ ♥ ♦, each with the eight cards **7, 8, 9, 10, J, Q, K, A**.'],
        rows: [{ label: 'All eight cards of one suit', cards: cards('H:7 8 9 10 J Q K A') }],
      },
      {
        kind: 'teach',
        title: 'The deal: 10 + 10 + 10 + 2',
        body: [
          'Everyone gets **10 cards**, and the last **2** go face down in the middle of the table — those two are the **skat**, which is where the game gets its name.',
          'Who gets the skat? The declarer. And who becomes declarer? That is decided by **bidding**, which has a whole lesson of its own later on.',
        ],
        rows: [{ label: 'The skat', cards: cards('C:7 8'), faceDown: true }],
      },
      {
        kind: 'teach',
        title: 'A deal in four steps',
        body: [
          '**① Bidding**: the three players bid against each other; the highest bidder becomes declarer.',
          '**② Announcing**: the declarer picks up the skat, puts two cards away, and announces what the game will be (which suit is trumps, and so on).',
          '**③ Playing**: everyone plays one card in turn; three cards make a **trick**, and the highest card takes it. There are 10 tricks.',
          '**④ Counting**: cards have point values, **120** in the whole deck. The declarer wins with **at least 61** card points in the tricks they took — just over half.',
        ],
        tip: '60 each? The declarer loses. The declarer needs "more than half"; half is not enough.',
      },
      { kind: 'choice', prompt: 'How many cards are in a Skat deck?', options: ['52', '36', '32', '24'], answer: 2, explain: 'Four suits × eight cards (7 to A) = 32 cards.' },
      { kind: 'choice', prompt: 'How are the sides formed in a deal?', options: ['Everyone plays for themselves', '1 declarer against 2 defenders', '2 against 2, with one watching', 'Fixed partners'], answer: 1, explain: 'In every deal the declarer plays alone against the other two. Partners are never fixed — next deal it might be you going it alone.' },
      { kind: 'choice', prompt: 'After the deal, how many cards lie face down in the skat?', options: ['1 card', '2 cards', '3 cards', '4 cards'], answer: 1, explain: '10 + 10 + 10 + **2** = 32. Those 2 skat cards belong to the declarer.' },
      { kind: 'choice', prompt: 'There are 120 card points in the deck. How many does the declarer need to win?', options: ['60', '61', '90', '100'], answer: 1, explain: '61 — just over half. 60 : 60 is a loss for the declarer.', hint: 'Think "more than half" — is exactly half enough?' },
    ],
  },
  {
    id: '2',
    title: 'Card points: which cards count',
    promise: 'See at a glance how many points a trick is worth.',
    emoji: '💰',
    minutes: 4,
    steps: [
      {
        kind: 'teach',
        title: 'Only five kinds of card score',
        body: ['When you win a trick, what you win is not "a trick" but the **card points** of its three cards. Only A, 10, K, Q and J are worth anything; 7, 8 and 9 score nothing and are called **blanks**.'],
        rows: [{ cards: cards('S:A 10 K Q J 9 8 7'), captions: ['11', '10', '4', '3', '2', '0', '0', '0'] }],
        tip: 'Memorise: A, 10, K, Q, J are worth **11, 10, 4, 3, 2**. Every suit has these five cards, adding up to 30 points; four suits make **120** — the 120 points of the whole deck from lesson 1.',
      },
      {
        kind: 'teach',
        title: 'Careful: the 10 beats the King',
        body: [
          'In Skat the **10 is the second-highest card**, right below the Ace — in points and in rank. A side suit ranks from high to low: **A, 10, K, Q, 9, 8, 7**.',
          '(Where did the Jack go? The Jacks are special — they are trumps. Next lesson.)',
        ],
        rows: [{ label: 'A side suit from high to low', cards: cards('D:A 10 K Q 9 8 7') }],
        tip: 'The classic beginner mistake: trying to beat a 10 with a King. It does not work.',
      },
      { kind: 'choice', prompt: 'Which of these cards is worth the most points?', options: ['K', 'Q', '10', 'J'], answer: 2, explain: 'The 10 is worth 10 points, second only to the Ace\'s 11. The King is worth just 4.' },
      ...times(4, countPointsDrill),
      { kind: 'choice', prompt: 'What is the most a single trick can be worth?', options: ['22', '30', '32', '33'], answer: 3, explain: 'Three Aces: 11 + 11 + 11 = **33** points. Impossible? Someone leads an Ace, the other two happen to have none of that suit and each throw an Ace of another suit on it — when a defender loads points onto a partner\'s trick, this really happens.', hint: 'The three cards need not be the same suit: a player without the suit that was led may play any card.' },
    ],
  },
  {
    id: '3',
    title: 'Trumps and the four Jacks',
    promise: 'Recognise the trumps in any game, and which one beats which.',
    emoji: '👑',
    minutes: 5,
    steps: [
      {
        kind: 'teach',
        title: 'Trumps beat everything',
        body: [
          'When announcing the game, the declarer names a suit as **trumps**. The privilege of trumps is simple: **any trump beats any card of another suit**. A trump 7 takes the Ace of a side suit.',
        ],
      },
      {
        kind: 'teach',
        title: 'The four Jacks: always on top',
        body: [
          "Skat's most famous rule: **the four Jacks are always trumps, and they are the four highest trumps**, whichever suit the declarer chooses.",
          'Among themselves the Jacks rank by suit: **♣J > ♠J > ♥J > ♦J**. The ♣J is the highest card in the game; Germans call it "der Alte" — "the old one".',
        ],
        rows: [{ label: 'Highest → lowest', cards: cards('C:J | S:J | H:J | D:J'), captions: ['1st', '2nd', '3rd', '4th'] }],
        tip: 'The suit order ♣ ♠ ♥ ♦ keeps coming back: it ranks the Jacks, and it ranks the suits\' base values too.',
      },
      {
        kind: 'teach',
        title: 'Hearts as trumps: 11 trumps',
        body: ['Say the declarer announces "Hearts". Then there are **11 trumps**: the four Jacks, plus the A, 10, K, Q, 9, 8, 7 of hearts. From high to low:'],
        rows: [{ cards: cards('C:J | S:J | H:J | D:J | H:A 10 K Q 9 8 7') }],
        tip: 'The ♥J ranks third not because it is a heart but because it is a Jack. Likewise, in a hearts game the ♣J is **not a club** — it is a trump.',
      },
      { kind: 'choice', prompt: 'How many trumps are there in a suit game?', options: ['8', '10', '11', '12'], answer: 2, explain: '4 Jacks + the other 7 cards of the trump suit (A 10 K Q 9 8 7) = **11**. Each of the three side suits keeps 7 cards.' },
      ...times(3, () => pickTrumpsDrill()),
      ...times(3, () => orderDrill()),
    ],
  },
  {
    id: '4',
    title: 'Following suit and winning tricks',
    promise: 'Know which cards you may play on your turn, and who takes the trick.',
    emoji: '🎯',
    minutes: 6,
    steps: [
      {
        kind: 'teach',
        title: 'Only one strict rule: follow if you can',
        body: [
          'One player **leads** a card to the trick, and the other two follow clockwise, one card each.',
          'There is just one rule: **if you hold a card of the suit that was led, you must play one**. You have none? Then you may play anything — a trump to take the trick (you **trump** it), or a worthless card you **throw off**.',
          'There is no rule that you must play higher. You may win if you can, or deliberately not.',
        ],
      },
      {
        kind: 'teach',
        title: 'Trumps count as a suit of their own',
        body: [
          'A trump was led? Then if you hold a trump you must play one — **Jacks included**, whatever suit is printed on them.',
          'The other way round: in a hearts game an opponent leads clubs, and your ♣J **may not** follow — it is not a club, it is a trump.',
        ],
        tip: 'This is the most common mistake in the whole course. Before you follow, ask: "Which suit does the lead count as?"',
      },
      {
        kind: 'play',
        prompt: 'Game: **Hearts ♥**. An opponent leads ♣A. Which card do you play?',
        contract: { kind: 'suit', trump: 'H' },
        hand: cards('C:J 7 | H:9 | D:A K'),
        trick: cards('C:A'),
        trickBy: ['Opponent'],
        explain: 'Your only real club is ♣7, so that is the only card you may play. The ♣J is a trump, not a club.',
      },
      {
        kind: 'teach',
        title: 'Who takes the trick',
        body: [
          '**Someone played a trump** → the highest trump wins.',
          '**Nobody played a trump** → the highest card **of the suit that was led** wins. A card of another suit cannot win, however high it is.',
          'The winner takes the three cards (their points go to that side) and **leads to the next trick**.',
        ],
      },
      ...times(3, () => legalDrill()),
      ...times(3, () => trickWinnerDrill()),
      {
        kind: 'play',
        prompt: 'Game: **Spades ♠**, and you are the declarer. The two defenders have played ♣10 and ♣K; your turn. Which card do you play?',
        contract: { kind: 'suit', trump: 'S' },
        hand: cards('S:9 | H:A 7 | D:K'),
        trick: cards('C:10 K'),
        trickBy: ['Defender', 'Defender'],
        best: cards('S:9'),
        whyNot: 'That card is allowed (you have no clubs, so anything goes), but there are 14 points on the table and you hold a trump — trump the trick.',
        explain: 'You have no clubs, so you may trump. The little ♠9 takes the ♣10 and ♣K together: 14 points for you.',
      },
    ],
  },
  {
    id: '5',
    title: 'Grand and Null',
    promise: 'Play the two other kinds of game: Grand, where only the Jacks are trumps, and Null, where you must not take a single trick.',
    emoji: '🎭',
    minutes: 6,
    steps: [
      {
        kind: 'teach',
        title: 'Three kinds of game',
        body: [
          'The declarer can choose more than the four suits. There are three kinds of game:',
          '**Suit games** — one of ♦ ♥ ♠ ♣ is trumps (the last two lessons).',
          '**Grand** — only the four Jacks are trumps.',
          '**Null** — no trumps at all, and the declarer\'s aim is turned upside down: take no trick.',
        ],
      },
      {
        kind: 'teach',
        title: 'Grand: only the Jacks rule',
        body: [
          'In Grand (said the French way, roughly "grahn") the only trumps are the four Jacks **♣J ♠J ♥J ♦J**. All four suits are side suits, each ranked A, 10, K, Q, 9, 8, 7.',
          'The goal stays the same: the declarer needs 61. Grand is the most valuable game — play it when you hold many Jacks and Aces.',
        ],
        rows: [{ label: 'All the trumps in Grand', cards: cards('C:J | S:J | H:J | D:J') }],
      },
      gen(() => pickTrumpsDrill({ kind: 'grand' })),
      ...times(2, () => trickWinnerDrill({ kind: 'grand' })),
      {
        kind: 'teach',
        title: 'Null: take nothing',
        body: [
          'Null turns everything around: **the moment the declarer takes any trick, they lose**. Only a declarer who takes no trick at all wins. Card points mean nothing in Null.',
          'Null has **no trumps**: each Jack goes back to its own suit as an ordinary card. And the ranking goes back to the "natural" one: **A, K, Q, J, 10, 9, 8, 7** — the 10 drops below the Jack.',
        ],
        rows: [{ label: 'One suit in Null, high to low', cards: cards('S:A K Q J 10 9 8 7') }],
        tip: 'A hand full of 7s, 8s and 9s? Don\'t sigh — it might be a beautiful Null.',
      },
      ...times(2, () => orderDrill({ kind: 'null' })),
      ...times(2, () => trickWinnerDrill({ kind: 'null' })),
      {
        kind: 'play',
        prompt: 'Game: **Null**, and you are the declarer. A defender leads ♣9. You hold three clubs — which is best?',
        contract: { kind: 'null' },
        hand: cards('C:Q 8 7 | H:7 8 | D:9'),
        trick: cards('C:9'),
        trickBy: ['Defender'],
        best: cards('C:8'),
        whyNot: 'Allowed, but not the best. The ♣Q is higher than the ♣9 — you might win the trick and lose the game on the spot. The ♣7 is safe, but it wastes a chance to get rid of a higher card.',
        explain: 'Play **the highest card that is still below the table**: the ♣8 ducks this trick and keeps the ♣7 as your life-saver for later.',
      },
    ],
  },
  {
    id: '6',
    title: 'What a game is worth',
    promise: 'Work out the value of any hand — the basis of all bidding.',
    emoji: '🧮',
    minutes: 7,
    steps: [
      {
        kind: 'teach',
        title: 'Game value = base value × multiplier',
        body: [
          'Every game has a **base value**, ranked by suit:',
          '**♦ Diamonds 9 · ♥ Hearts 10 · ♠ Spades 11 · ♣ Clubs 12 · Grand 24**',
          'What the game is actually worth is the base value times a **multiplier**. Where does the multiplier come from? Start with the matadors.',
        ],
        tip: 'Null is not multiplied — it has fixed values (from 23 up), covered in lesson 9.',
      },
      {
        kind: 'teach',
        title: 'Matadors: count down from ♣J',
        body: [
          'Line up the trumps from high to low: ♣J, ♠J, ♥J, ♦J, then A, 10, K… of the trump suit.',
          '**You hold ♣J** → count how many trumps you hold **in an unbroken run** from it downwards: you are "**with** that many". ♣J ♠J but no ♥J = with 2.',
          "**You don't hold ♣J** → count how many trumps in a row you are **missing** from the top: you are \"**without** that many\". Missing ♣J ♠J, holding ♥J = without 2.",
          '"With" and "without" are worth exactly the same. And when you count, **the skat counts as the declarer\'s cards too**.',
        ],
        rows: [
          { label: 'With 2 (broken at ♥J)', cards: cards('C:J | S:J | D:J | H:A') },
          { label: 'Without 2 (holding starts at ♥J)', cards: cards('H:J | D:J | H:A 10') },
        ],
      },
      {
        kind: 'teach',
        title: 'Multiplier = matadors + 1 + extras',
        body: [
          'Multiplier = the number of matadors, **+1** (for playing at all — "game"), plus any extras (Hand, Schneider… lessons 8 and 9).',
          'Example: you play Hearts holding ♣J ♠J but not ♥J. With 2, game 3. Hearts has base value 10 → **10 × 3 = 30**.',
          'Example: you play Clubs without a single Jack; your highest trump is ♣A. Without 4, game 5 → **12 × 5 = 60**.',
        ],
        tip: 'At the table you count it out loud just like this: "With 2, game 3, times 10: thirty."',
      },
      ...times(3, matadorDrill),
      ...times(3, gameValueDrill),
    ],
  },
  {
    id: '7',
    title: 'Bidding',
    promise: 'Understand — and join in — the table talk that goes "18?" — "Yes." "20?" — "Pass."',
    emoji: '📣',
    minutes: 7,
    steps: [
      {
        kind: 'teach',
        title: 'What you are bidding',
        body: [
          'Bidding decides who is declarer. Each bid is a **number**, meaning: "the game I intend to play is worth at least this much." Whoever dares bid highest becomes declarer.',
          'So before you bid, look at your cards, decide what you would play, and work out its value the way the last lesson showed — **that is as high as you can bid**.',
          'The lowest bid is **18** (Diamonds, with or without 1: 9 × 2).',
        ],
      },
      {
        kind: 'teach',
        title: 'The three seats',
        body: [
          '**Forehand**: the player on the dealer\'s left. Forehand leads to the first trick.',
          '**Middlehand**: the next player after forehand.',
          '**Rearhand**: the dealer.',
          'Bidding is two duels: **first middlehand bids to forehand** until one of them drops out; **then rearhand challenges the survivor**.',
        ],
      },
      {
        kind: 'teach',
        title: 'How a duel goes',
        body: [
          'One player **bids** numbers, the other **answers**. The bidder names a number, and the answer is one word: **"Yes"** (I would play that too) or **"Pass"** (I drop out).',
          'Middlehand: "18?" — Forehand: "Yes."',
          'Middlehand: "20?" — Forehand: "Yes."',
          'Middlehand: "22?" — Forehand: "Pass." → Middlehand wins; the bid stands at 22.',
          'Then rearhand bids to middlehand: "23?" … until one of them passes. The last one left is the declarer, and the game they play **must be worth at least the final bid**.',
        ],
        tip: 'Answering is the easier seat: you only have to keep up, not go higher. With the same cards, forehand is the most likely to become declarer.',
      },
      {
        kind: 'teach',
        title: 'The bidding ladder',
        body: [
          'You may only bid numbers that a game can actually be worth:',
          '**18 · 20 · 22 · 23 · 24 · 27 · 30 · 33 · 35 · 36 · 40 · 44 · 45 · 46 · 48 · 50 …**',
          'They are the multiples of 9, 10, 11, 12 and 24 (from 2× up), plus the four fixed Null values 23, 35, 46, 59.',
          'If nobody wants to bid (forehand will not even take 18), the deal is **passed in** and dealt again.',
        ],
      },
      { kind: 'choice', prompt: 'Who names the first number in the bidding?', options: ['Forehand', 'Middlehand', 'Rearhand', 'Whoever the dealer picks'], answer: 1, explain: 'Middlehand bids to forehand first, and forehand answers "Yes" or "Pass". Rearhand waits for the winner of that duel.' },
      { kind: 'choice', prompt: 'After "18", what is the next number you may bid?', options: ['19', '20', '21', '24'], answer: 1, explain: '20 = Hearts 10 × 2. No game is worth 19 or 21, so nobody may bid them.' },
      { kind: 'choice', prompt: 'Which game does the 23 on the ladder belong to?', options: ['Diamonds × 2.5', 'A plain Null', 'Grand', 'Spades Hand'], answer: 1, explain: '23 is the fixed value of a plain Null — deliberately placed between 22 and 24, so that a good Null hand can outbid the cheapest suit game.' },
      ...times(2, gameValueDrill),
      { kind: 'choice', prompt: 'Your hand is worth 30 as a hearts game. An opponent bids "33?" to you. What do you answer?', options: ['"Yes" — never back down', '"Pass"', '"36!" — outbid them', 'Say nothing'], answer: 1, explain: 'Saying "Yes" commits you to a game worth at least 33, and yours is worth 30 — that is an **overbid**, lost however you play, and at double cost.', hint: 'Your limit is 30. And 33 is…' },
      {
        kind: 'teach',
        title: 'What is worth bidding?',
        body: [
          'Rough guidelines (on average the skat improves your hand by about one card):',
          '**Suit game**: at least 5 trumps (Jacks included), plus an Ace or two on the side.',
          '**Grand**: at least two or three Jacks (ideally ♣J), plus two or three Aces.',
          '**Null**: a 7 or an 8 at the bottom of every suit, and no lonely high cards.',
          'Nothing fits? Then pass and play defence with a clear mind — when the defenders win, you win too.',
        ],
      },
    ],
  },
  {
    id: '8',
    title: 'The skat, discarding and Hand',
    promise: 'Once you are declarer, know how to make the most of the two skat cards.',
    emoji: '🗃️',
    minutes: 6,
    steps: [
      {
        kind: 'teach',
        title: "The declarer's privilege",
        body: [
          'Won the bidding? You are the declarer. Next:',
          '**① Pick up the two skat cards** — you now hold 12.',
          '**② Put two cards away face down** (the ones you just picked up, or any others).',
          '**③ Announce the game.**',
          'The two cards you put away take no part in play, but their **card points count for the declarer** — money in the bank before the first card is played.',
        ],
      },
      {
        kind: 'teach',
        title: 'Which two? Three rules of thumb',
        body: [
          '**Bank points**: a singleton 10 with no Ace to protect it is easily caught by an opponent\'s Ace. Put it away and those 10 points are safe.',
          '**Make a void**: put away every card of a side suit. Whenever an opponent leads that suit later, you can trump it.',
          "**Don't discard trumps or Aces**: they are what win you tricks.",
        ],
      },
      {
        kind: 'choice',
        prompt: 'You are the declarer and plan to play **Hearts ♥**. After picking up the skat you hold these 12 cards. Which two should you put away?',
        rows: [{ cards: cards('C:J | H:J A 10 K 9 | S:A 7 | C:10 | D:K 8 7') }],
        options: ['♣10 and ♦K', '♠A and ♠7', '♥9 and ♦7', '♦8 and ♦7'],
        answer: 0,
        explain: 'The ♣10 stands alone: the moment an opponent plays ♣A, it gives away 10 points. Put it away and bank the 10 — and you are now void in clubs, so you can trump them later. Add the ♦K for 4 more and you already have 14 points in the skat.',
        hint: 'Which card is valuable but cannot be kept safe? Which suit is empty after putting one card away?',
      },
      {
        kind: 'teach',
        title: 'Hand: not looking at the skat',
        body: [
          'Hand good enough already? You can announce **Hand**: you **leave the skat where it is** and play with the 10 cards you were dealt. The reward: **+1** to the multiplier.',
          'The skat is still yours: its points count for you after play, and **it counts when you count your matadors**.',
          'That is exactly the risk of Hand: a Jack hidden in the skat can quietly change your matadors.',
        ],
      },
      {
        kind: 'choice',
        prompt: 'Your highest trump is the ♥J (no ♣J, no ♠J), so you play Spades Hand "without 2": 11 × (2 + 1 + 1) = 44, and you bid 44. After play the skat is turned over — and it holds the **♣J**. What now?',
        options: ['Nothing changes: still 44', 'It becomes "with 1": 11 × 3 = 33 — you overbid', 'It becomes "with 3" — worth more', "The skat doesn't count, so it doesn't matter"],
        answer: 1,
        explain: 'The skat counts as the declarer\'s. With the ♣J you are "with", but the ♠J is not yours, so only "with 1": multiplier 1 + 1 + 1 = 3, game value 33 < your bid of 44 — an **overbid**, and the game is lost. Playing a Hand game "without", always leave some margin.',
        hint: 'The ♣J is yours now. Counting down from ♣J, how many trumps in a row do you hold?',
      },
      { kind: 'choice', prompt: 'In a Hand game, who gets the points of the two unseen skat cards in the end?', options: ['The defenders', 'The declarer', 'Whoever wins the last trick', 'Nobody — they don\'t count'], answer: 1, explain: 'The skat always belongs to the declarer, looked at or not.' },
    ],
  },
  {
    id: '9',
    title: 'Extras and scoring',
    promise: 'Score a finished game yourself — big wins, heavy losses and overbids included.',
    emoji: '🏆',
    minutes: 6,
    steps: [
      {
        kind: 'teach',
        title: 'Schneider and Schwarz',
        body: [
          'Win big, and the multiplier grows:',
          '**Schneider**: the losing side has **30 card points or fewer** (so the winners have ≥ 90). Multiplier **+1**.',
          '**Schwarz**: the losing side took **no trick at all**. Multiplier **+1 more**.',
          'Careful — it cuts both ways. A declarer who ends with 30 or fewer pays for the Schneider too, and then the loss is doubled.',
        ],
      },
      {
        kind: 'teach',
        title: 'Announcing: only in Hand',
        body: [
          'A declarer playing Hand may also make bold promises before play; each one adds **+1** to the multiplier:',
          '**Announce Schneider** — "I will take at least 90."',
          '**Announce Schwarz** — "I will take all ten tricks."',
          '**Ouvert** (open) — "I play with my hand face up on the table, and I still take all ten tricks."',
          'Announce it and miss — even with 89 — and the game is lost.',
        ],
      },
      {
        kind: 'teach',
        title: 'The four fixed Null values',
        body: ['Null has no matadors, only four fixed values:', '**Null 23 · Null Hand 35 · Null Ouvert 46 · Null Ouvert Hand 59**', 'Null Ouvert means playing Null with your hand face up — only for a hand of low cards that nothing can break.'],
      },
      {
        kind: 'teach',
        title: 'Scoring',
        body: [
          '**Declarer wins**: + the game value.',
          '**Declarer loses**: − **2 ×** the game value. A loss costs twice what a win brings, so don\'t bid recklessly.',
          '**Overbid**: the game turns out worth less than the bid — lost whatever the card points. It is scored at the smallest multiple of the base value that reaches the bid, and doubled.',
          'The defenders get no separate score — the declarer\'s result is the whole score of the deal. After a number of deals, the highest total wins.',
        ],
        tip: 'Official tournaments also give the declarer +50 for each game won and −50 for each game lost, and the defenders a bonus. Home games usually leave that out.',
      },
      ...times(4, settleDrill),
      { kind: 'choice', prompt: 'What is a Null Ouvert (skat picked up, played face up) worth?', options: ['23', '35', '46', '59'], answer: 2, explain: '23 (plain) → 35 (Hand) → **46 (Ouvert)** → 59 (Ouvert Hand).' },
      { kind: 'choice', prompt: 'The declarer ends with 89 card points. Is that Schneider?', options: ['Yes', 'No, it takes 90', 'Depends on whether the defenders took a trick', 'Only in a Hand game'], answer: 1, explain: 'The defenders must have 30 or fewer, which means the declarer needs 90. 89 : 31 — just short.' },
    ],
  },
  {
    id: '10',
    title: 'How to play: declarer and defence basics',
    promise: 'Stop just playing legal cards — know why you play each one.',
    emoji: '🧠',
    minutes: 8,
    steps: [
      {
        kind: 'teach',
        title: "The declarer's plan: draw trumps, then collect",
        body: [
          "What the declarer fears most: an opponent trumping one of the declarer's Aces with a small trump.",
          'So the declarer usually starts by **leading high trumps one after another**, forcing both opponents to follow with theirs until they have none left (**drawing trumps**). There are 11 trumps: how many you hold and how many have been played tells you how many the opponents still have — **counting trumps** is skill number one.',
          'Once the opponents are out of trumps, your side-suit Aces and 10s are truly safe points.',
        ],
      },
      {
        kind: 'play',
        prompt: 'Game: **Hearts ♥**. You are the declarer and lead to the first trick. Which card?',
        contract: { kind: 'suit', trump: 'H' },
        hand: cards('C:J | S:J | H:A 10 9 | S:A 10 | C:7 | D:8 7'),
        trick: [],
        best: cards('C:J | S:J'),
        whyNot: 'Too early. The opponents still hold 6 trumps, and your Ace could easily be trumped by a small one. Draw trumps with your high Jacks first.',
        explain: 'Nobody can beat the ♣J, so leading it wins for sure and pulls two of the opponents\' trumps. Then the ♠J, the ♥A… once the opponents are out of trumps, the ♠A and ♠10 are 21 free points.',
      },
      {
        kind: 'teach',
        title: "The defenders' plan: feed your partner",
        body: [
          'The two defenders are one side, and their card points are added together. So their most important move is to **smear**:',
          '**Your partner is going to win this trick** → put your fattest card (an A or 10) on it, so the trick is worth more.',
          '**The declarer is going to win this trick** → throw off your most worthless blank; give nothing away.',
          'Also: defenders **should not lead trumps** themselves — that draws trumps for the declarer. If you hold a side-suit Ace, take your trick with it early.',
        ],
      },
      {
        kind: 'play',
        prompt: 'Game: **Spades ♠**, and you are a defender. Your partner leads ♦A, the declarer follows with ♦7. Your turn — which card?',
        contract: { kind: 'suit', trump: 'S' },
        hand: cards('D:10 8 | H:K 9 | C:Q'),
        trick: cards('D:A 7'),
        trickBy: ['Partner', 'Declarer'],
        best: cards('D:10'),
        whyNot: "Allowed, but a missed chance. Your partner's ♦A has already won — this is the moment to add your fattest card.",
        explain: 'Smear! ♦A + ♦7 + ♦10 = 21 points, all for your side. With the ♦8 it would be just 11.',
      },
      {
        kind: 'play',
        prompt: 'Game: **Clubs ♣**, and you are a defender. The declarer leads ♣J, your partner follows with ♣9. You must follow with a trump — which one?',
        contract: { kind: 'suit', trump: 'C' },
        hand: cards('C:10 8 | D:A | H:7'),
        trick: cards('C:J 9'),
        trickBy: ['Declarer', 'Partner'],
        best: cards('C:8'),
        whyNot: 'The ♣J is the highest card in the game: the declarer has won this trick. The ♣10 would just hand over 10 points.',
        explain: "If you can't win, play low. Keep the ♣10 — it may still take a trick later.",
      },
      {
        kind: 'play',
        prompt: 'Game: **Hearts ♥**. You are the declarer and play last. The defenders have played ♠10 and ♠A, and you have no spades. Which card?',
        contract: { kind: 'suit', trump: 'H' },
        hand: cards('H:J 7 | D:K 9 | C:8'),
        trick: cards('S:10 A'),
        trickBy: ['Defender', 'Defender'],
        best: cards('H:7'),
        whyNot: "There are 21 points on the table — take them! And since you play last, nobody can beat you afterwards: your smallest trump is enough. Keep the big ones.",
        explain: 'When you play last, win with the smallest card that is "just enough". The ♥7 takes 21 points and the ♥J stays in your hand for later.',
      },
      { kind: 'choice', prompt: 'Hearts game, you are the declarer with 6 trumps. 3 trumps have been played so far, 2 of them by the opponents. How many trumps do the opponents still have?', options: ['2', '3', '4', '5'], answer: 1, explain: 'There are 11 trumps. You hold 6, so the opponents started with 5; they have played 2, so **3** are left.', hint: '11 trumps − your 6 = how many did the opponents start with?' },
      { kind: 'choice', prompt: 'What should a defender usually **not** lead?', options: ['A side-suit Ace', 'A trump', 'A small card of a short suit', "A suit your partner has shown"], answer: 1, explain: "Leading trumps draws them for the declarer. A defender's trumps are for trumping the declarer's Aces and 10s." },
    ],
  },
  {
    id: '11',
    title: 'Graduation game: take a seat!',
    promise: 'Play a complete game against two computer opponents. After that, you can play Skat.',
    emoji: '🎓',
    minutes: 10,
    steps: [
      {
        kind: 'teach',
        title: 'Cheat sheet for the table',
        body: [
          '**Card points** A 11 · 10 10 · K 4 · Q 3 · J 2 | declarer needs **61**',
          '**Trumps** ♣J ♠J ♥J ♦J, then the trump suit A 10 K Q 9 8 7',
          '**Following** follow suit if you can; a Jack is a trump, not the suit printed on it',
          '**Base values** ♦9 ♥10 ♠11 ♣12 Grand 24 | Null 23/35/46/59',
          '**Game value** base value × (matadors + 1 + extras)',
          '**Bidding** middlehand → forehand, rearhand → the winner; bid only up to your own game value',
        ],
        tip: 'During the game you can tap "Hint" at any time: it tells you which card to play and why. Don\'t be afraid to lose — you learn more from a lost game than from a won one.',
      },
      {
        kind: 'game',
        title: 'Play a whole game',
        body: ['Bidding, the skat, announcing, ten tricks, scoring — the whole thing once through. Win or lose: when it is over, you have graduated.'],
      },
    ],
  },
]
