// Der Kurs auf Deutsch — dieselben elf Lektionen, Karten und Antworten wie content.zh.ts
// (lessons.test.ts hält die drei Sprachen daran fest). Begriffe nach der Internationalen Skatordnung
// (DSkV): Alleinspieler, Gegenspieler, Vorhand / Mittelhand / Hinterhand, Stich, Augen, reizen,
// drücken, Spitzen „mit / ohne“. Karten werden mit den deutschen Buchstaben zitiert (♣B = Kreuz-Bube,
// ♠D = Pik-Dame); die abgebildeten Karten tragen englische Indizes (J, Q), was Lektion 1 einmal
// erklärt. Entscheidungen und Quellen: .intentfold/tickets/SKATGO-1/terms.md.

import { cards } from '../cards'
import {
  countPointsDrill,
  gameValueDrill,
  legalDrill,
  matadorDrill,
  orderDrill,
  pickTrumpsDrill,
  settleDrill,
  trickWinnerDrill,
} from './drills'
import { gen, times } from './build'
import type { Lesson } from './types'

export const LESSONS_DE: Lesson[] = [
  {
    id: '1',
    title: 'Drei Spieler, 32 Karten',
    promise: 'Wissen, worum es beim Skat geht: wer gegen wen spielt, worum und wie man gewinnt.',
    emoji: '🃏',
    minutes: 1,
    steps: [
      {
        kind: 'teach',
        title: 'Das deutsche Nationalkartenspiel',
        body: [
          'Skat ist ein Stichspiel für drei Personen, und in Deutschland kennt es fast jeder. Es hat nur 32 Karten, ein Spiel dauert zehn Minuten – und trotzdem braucht man Rechnen, Gedächtnis und Mut zugleich.',
          'Das Besondere: In jedem Spiel heißt es **einer gegen zwei**. Wer allein spielt, ist der **Alleinspieler**; die anderen beiden tun sich für dieses Spiel als **Gegenspieler** zusammen. Wer im nächsten Spiel allein spielt? Das wird neu ausgereizt.',
        ],
        tip: 'Der Kurs hat 11 Lektionen. Jede erklärt erst und lässt dich dann üben, und in der letzten spielst du eine ganze Partie gegen zwei Computergegner – danach bist du bereit für einen echten Skattisch.',
      },
      {
        kind: 'teach',
        title: '32 Karten',
        body: [
          'Nimm aus einem normalen Kartenspiel die 2 bis 6 und die Joker heraus, dann bleibt ein Skatblatt übrig: vier Farben ♣ ♠ ♥ ♦ mit je acht Karten **7, 8, 9, 10, Bube, Dame, König, Ass**.',
          'Kurz geschrieben: **7, 8, 9, 10, B, D, K, A**. Die Karten in diesem Kurs tragen englische Buchstaben – beim Buben steht **J**, bei der Dame **Q**. Auf einem deutschen Turnierblatt steht dort **B** und **D**; im Text schreiben wir es deshalb so, wie man es am Tisch sagt.',
        ],
        rows: [{ label: 'Alle acht Karten einer Farbe', cards: cards('H:7 8 9 10 J Q K A') }],
      },
      {
        kind: 'teach',
        title: 'Das Geben: 10 + 10 + 10 + 2',
        body: [
          'Jeder bekommt **10 Karten**, die letzten **2** liegen verdeckt in der Tischmitte – das ist der **Skat**, nach dem das Spiel benannt ist.',
          'Wem gehört der Skat? Dem Alleinspieler. Und wer wird Alleinspieler? Das entscheidet das **Reizen**, dem später eine ganze Lektion gehört.',
        ],
        rows: [{ label: 'Der Skat', cards: cards('C:7 8'), faceDown: true }],
      },
      {
        kind: 'teach',
        title: 'Ein Spiel in vier Schritten',
        body: [
          '**① Reizen**: Die drei bieten gegeneinander; wer am höchsten reizt, wird Alleinspieler.',
          '**② Ansagen**: Der Alleinspieler nimmt den Skat auf, drückt zwei Karten und sagt an, was gespielt wird (welche Farbe Trumpf ist und so weiter).',
          '**③ Spielen**: Reihum legt jeder eine Karte; drei Karten sind ein **Stich**, die höchste bekommt ihn. Es gibt 10 Stiche.',
          '**④ Zählen**: Die Karten haben **Augen**, im ganzen Blatt **120**. Der Alleinspieler gewinnt mit **mindestens 61 Augen** – also knapp mehr als der Hälfte.',
        ],
        tip: '60 zu 60? Dann verliert der Alleinspieler. Er braucht „mehr als die Hälfte“; genau die Hälfte reicht nicht.',
      },
      { kind: 'choice', prompt: 'Wie viele Karten hat ein Skatblatt?', options: ['52', '36', '32', '24'], answer: 2, explain: 'Vier Farben × acht Karten (7 bis Ass) = 32 Karten.' },
      { kind: 'choice', prompt: 'Wie werden die Seiten in einem Spiel gebildet?', options: ['Jeder spielt für sich', '1 Alleinspieler gegen 2 Gegenspieler', '2 gegen 2, einer schaut zu', 'Feste Partner'], answer: 1, explain: 'In jedem Spiel spielt der Alleinspieler gegen die beiden anderen. Feste Partner gibt es nicht – im nächsten Spiel spielst vielleicht du allein.' },
      { kind: 'choice', prompt: 'Wie viele Karten liegen nach dem Geben verdeckt im Skat?', options: ['1 Karte', '2 Karten', '3 Karten', '4 Karten'], answer: 1, explain: '10 + 10 + 10 + **2** = 32. Diese 2 Karten gehören dem Alleinspieler.' },
      { kind: 'choice', prompt: 'Das Blatt hat 120 Augen. Wie viele braucht der Alleinspieler mindestens zum Gewinnen?', options: ['60', '61', '90', '100'], answer: 1, explain: '61 – knapp mehr als die Hälfte. Bei 60 : 60 verliert der Alleinspieler.', hint: 'Denk an „mehr als die Hälfte“ – reicht genau die Hälfte?' },
    ],
  },
  {
    id: '2',
    title: 'Augen: welche Karten zählen',
    promise: 'Auf einen Blick sehen, wie viele Augen ein Stich hat.',
    emoji: '💰',
    minutes: 1,
    steps: [
      {
        kind: 'teach',
        title: 'Nur fünf Kartenwerte zählen',
        body: ['Wer einen Stich bekommt, gewinnt nicht „einen Stich“, sondern die **Augen** seiner drei Karten. Nur Ass, Zehn, König, Dame und Bube zählen; 7, 8 und 9 sind nichts wert und heißen **Luschen**.'],
        rows: [{ cards: cards('S:A 10 K Q J 9 8 7'), captions: ['11', '10', '4', '3', '2', '0', '0', '0'] }],
        tip: 'Merke: A, 10, K, D, B zählen **11, 10, 4, 3, 2**. Jede Farbe hat diese fünf Karten, zusammen 30 Augen; vier Farben ergeben **120** – die 120 Augen des ganzen Blatts aus Lektion 1.',
      },
      {
        kind: 'teach',
        title: 'Achtung: Die Zehn schlägt den König',
        body: [
          'Beim Skat ist die **Zehn die zweithöchste Karte**, direkt nach dem Ass – bei den Augen wie im Rang. Eine Fehlfarbe geht von oben nach unten so: **A, 10, K, D, 9, 8, 7**.',
          '(Wo ist der Bube? Die Buben sind etwas Besonderes – sie sind Trumpf. Nächste Lektion.)',
        ],
        rows: [{ label: 'Eine Fehlfarbe von hoch nach niedrig', cards: cards('D:A 10 K Q 9 8 7') }],
        tip: 'Der klassische Anfängerfehler: mit dem König die Zehn schlagen wollen. Das geht nicht.',
      },
      { kind: 'choice', prompt: 'Welche dieser Karten hat die meisten Augen?', options: ['K', 'D', '10', 'B'], answer: 2, explain: 'Die Zehn zählt 10 Augen, nur das Ass mit 11 zählt mehr. Der König hat bloß 4.' },
      ...times(4, countPointsDrill),
      { kind: 'choice', prompt: 'Wie viele Augen kann ein einzelner Stich höchstens haben?', options: ['22', '30', '32', '33'], answer: 3, explain: 'Drei Asse: 11 + 11 + 11 = **33** Augen. Unmöglich? Einer spielt ein Ass aus, die beiden anderen haben die Farbe zufällig nicht und werfen je ein Ass einer anderen Farbe ab – wenn ein Gegenspieler seinem Partner Augen schmiert, passiert genau das.', hint: 'Die drei Karten müssen nicht dieselbe Farbe haben: Wer die ausgespielte Farbe nicht hat, darf jede Karte spielen.' },
    ],
  },
  {
    id: '3',
    title: 'Trumpf und die vier Buben',
    promise: 'In jedem Spiel die Trümpfe erkennen – und wer wen sticht.',
    emoji: '👑',
    minutes: 1,
    steps: [
      {
        kind: 'teach',
        title: 'Trumpf sticht alles',
        body: [
          'Beim Ansagen bestimmt der Alleinspieler eine Farbe als **Trumpf**. Das Vorrecht des Trumpfs ist einfach: **Jeder Trumpf sticht jede Karte einer anderen Farbe**. Eine Trumpf-7 sticht das Ass einer Fehlfarbe.',
        ],
      },
      {
        kind: 'teach',
        title: 'Die vier Buben: immer ganz oben',
        body: [
          'Die berühmteste Regel beim Skat: **Die vier Buben sind immer Trumpf, und zwar die vier höchsten Trümpfe** – egal, welche Farbe der Alleinspieler wählt.',
          'Untereinander gilt die Farbe: **♣B > ♠B > ♥B > ♦B**. Der Kreuz-Bube ist die höchste Karte im Spiel; man nennt ihn „den Alten“.',
        ],
        rows: [{ label: 'Höchster → niedrigster', cards: cards('C:J | S:J | H:J | D:J'), captions: ['1.', '2.', '3.', '4.'] }],
        tip: 'Die Farbreihenfolge ♣ ♠ ♥ ♦ begegnet dir immer wieder: Nach ihr richten sich die Buben und auch die Grundwerte der Farben.',
      },
      {
        kind: 'teach',
        title: 'Beispiel Herz: 11 Trümpfe',
        body: ['Angenommen, der Alleinspieler sagt „Herz“ an. Dann gibt es **11 Trümpfe**: die vier Buben, dazu Herz-Ass, -10, -König, -Dame, -9, -8, -7. Von hoch nach niedrig:'],
        rows: [{ cards: cards('C:J | S:J | H:J | D:J | H:A 10 K Q 9 8 7') }],
        tip: 'Der ♥B steht an dritter Stelle, nicht weil er Herz ist, sondern weil er ein Bube ist. Ebenso ist der ♣B im Herzspiel **kein Kreuz** – er ist Trumpf.',
      },
      { kind: 'choice', prompt: 'Wie viele Trümpfe gibt es in einem Farbspiel?', options: ['8', '10', '11', '12'], answer: 2, explain: '4 Buben + die übrigen 7 Karten der Trumpffarbe (A 10 K D 9 8 7) = **11**. Die drei Fehlfarben haben je 7 Karten.' },
      ...times(3, () => pickTrumpsDrill()),
      ...times(3, () => orderDrill()),
    ],
  },
  {
    id: '4',
    title: 'Bedienen und Stiche gewinnen',
    promise: 'Wissen, welche Karten du spielen darfst – und wem der Stich gehört.',
    emoji: '🎯',
    minutes: 2,
    steps: [
      {
        kind: 'teach',
        title: 'Bedienen: Hast du die Farbe, musst du sie spielen',
        body: [
          'In jedem Stich legt einer die erste Karte – er **spielt aus**. Ihre Farbe ist die Farbe des Stichs. Danach legen die anderen beiden im Uhrzeigersinn je eine Karte dazu – sie **geben zu**.',
          'Dafür gibt es eine feste Regel: **Hast du irgendeine Karte der ausgespielten Farbe, musst du diese Farbe spielen** – man sagt: Farbe **bedienen**. Welche Karte davon, entscheidest du, hoch oder niedrig.',
          'Im Spiel unten ist **Kreuz Trumpf**. Ein Gegner spielt das ♥A aus (Herz). Du hast Herz, also musst du eine deiner beiden Herzkarten nehmen:',
        ],
        rows: [
          { label: 'Ausgespielt', cards: cards('H:A') },
          { label: 'Deine Karten: ✓ erlaubt, ✗ nicht erlaubt', cards: cards('H:10 7 | S:K | D:9'), follow: { contract: { kind: 'suit', trump: 'C' }, lead: cards('H:A')[0] } },
          { label: 'Ohne eine einzige Herzkarte darfst du jede Karte spielen', cards: cards('C:8 | S:K | D:9'), captions: ['stechen', 'abwerfen', 'abwerfen'] },
        ],
        tip: 'Hast du die ausgespielte Farbe nicht: Nimmst du den Stich mit einem **Trumpf**, heißt das **stechen**; legst du eine nutzlose Karte einer anderen Farbe, heißt das **abwerfen**. Einen Zwang, höher zu spielen, gibt es übrigens nicht – du darfst gewinnen, musst aber nicht.',
      },
      {
        kind: 'teach',
        title: 'Ein Bube gehört nicht zu seiner Farbe – er ist Trumpf',
        body: [
          'Lektion 3 sagt: Die vier Buben sind immer Trumpf. Beim Bedienen gehört ein Bube deshalb **nicht zu der Farbe, die auf ihm steht** – er gehört zu den Trümpfen.',
          'Im Spiel unten ist **Herz Trumpf**. Du hast zweimal dieselben vier Karten; nur die ausgespielte Karte ist anders:',
          '**♣A ausgespielt (Kreuz)** → nur ein echtes Kreuz, die ♣7, ist erlaubt. Auf dem ♣B steht zwar Kreuz, aber er ist Trumpf und bedient kein Kreuz.',
          '**♥A ausgespielt (Trumpf)** → deine Trümpfe sind ♣B und ♥9, eine davon musst du spielen.',
        ],
        rows: [
          { label: 'Wenn ♣A ausgespielt wird', cards: cards('C:J 7 | H:9 | D:K'), follow: { contract: { kind: 'suit', trump: 'H' }, lead: cards('C:A')[0] } },
          { label: 'Wenn ♥A ausgespielt wird', cards: cards('C:J 7 | H:9 | D:K'), follow: { contract: { kind: 'suit', trump: 'H' }, lead: cards('H:A')[0] } },
        ],
        tip: 'Das ist der häufigste Fehler im ganzen Kurs. Frag dich vor jedem Zugeben: „Als welche Farbe zählt die ausgespielte Karte?“',
      },
      {
        kind: 'play',
        prompt: 'Spiel: **Herz ♥**. Ein Gegner spielt ♣A aus. Welche Karte spielst du?',
        contract: { kind: 'suit', trump: 'H' },
        hand: cards('C:J 7 | H:9 | D:A K'),
        trick: cards('C:A'),
        trickBy: ['Gegner'],
        explain: 'Dein einziges echtes Kreuz ist die ♣7, also darfst du nur sie spielen. Der ♣B ist Trumpf, kein Kreuz.',
      },
      {
        kind: 'teach',
        title: 'Wem gehört der Stich?',
        body: [
          '**Jemand hat Trumpf gespielt** → der höchste Trumpf gewinnt.',
          '**Niemand hat Trumpf gespielt** → die höchste Karte **der ausgespielten Farbe** gewinnt. Eine abgeworfene andere Farbe gewinnt nie, egal wie hoch.',
          'Wer gewinnt, nimmt die drei Karten (ihre Augen zählen für seine Seite) und **spielt zum nächsten Stich aus**.',
        ],
      },
      ...times(3, () => legalDrill()),
      ...times(3, () => trickWinnerDrill()),
      {
        kind: 'play',
        prompt: 'Spiel: **Pik ♠**, du bist Alleinspieler. Die beiden Gegenspieler haben ♣10 und ♣K gelegt, du bist dran. Welche Karte spielst du?',
        contract: { kind: 'suit', trump: 'S' },
        hand: cards('S:9 | H:A 7 | D:K'),
        trick: cards('C:10 K'),
        trickBy: ['Gegenspieler', 'Gegenspieler'],
        best: cards('S:9'),
        whyNot: 'Die Karte ist erlaubt (du hast kein Kreuz, also darfst du alles spielen), aber es liegen 14 Augen auf dem Tisch, und du hast Trumpf – stich den Stich.',
        explain: 'Du hast kein Kreuz, also darfst du stechen. Die kleine ♠9 holt ♣10 und ♣K zusammen: 14 Augen für dich.',
      },
    ],
  },
  {
    id: '5',
    title: 'Grand und Null',
    promise: 'Die beiden anderen Spielarten beherrschen: Grand, in dem nur die Buben Trumpf sind, und Null, in dem man keinen Stich bekommen darf.',
    emoji: '🎭',
    minutes: 2,
    steps: [
      {
        kind: 'teach',
        title: 'Drei Spielarten',
        body: [
          'Der Alleinspieler kann mehr wählen als die vier Farben. Es gibt drei Spielarten:',
          '**Farbspiel** – eine von ♦ ♥ ♠ ♣ ist Trumpf (die letzten beiden Lektionen).',
          '**Grand** – nur die vier Buben sind Trumpf.',
          '**Null** – gar kein Trumpf, und das Ziel des Alleinspielers ist umgedreht: keinen einzigen Stich bekommen.',
        ],
      },
      {
        kind: 'teach',
        title: 'Grand: nur die Buben zählen',
        body: [
          'Im Grand sind nur die vier Buben **♣B ♠B ♥B ♦B** Trumpf. Alle vier Farben sind Fehlfarben, jede in der Reihenfolge A, 10, K, D, 9, 8, 7.',
          'Das Ziel bleibt: Der Alleinspieler braucht 61. Der Grand ist das wertvollste Spiel – man spielt ihn mit vielen Buben und Assen.',
        ],
        rows: [{ label: 'Alle Trümpfe im Grand', cards: cards('C:J | S:J | H:J | D:J') }],
      },
      gen(() => pickTrumpsDrill({ kind: 'grand' })),
      ...times(2, () => trickWinnerDrill({ kind: 'grand' })),
      {
        kind: 'teach',
        title: 'Null: bloß keinen Stich',
        body: [
          'Null stellt alles auf den Kopf: **Sobald der Alleinspieler einen Stich bekommt, hat er verloren**. Nur wer keinen einzigen Stich bekommt, gewinnt. Augen spielen im Null keine Rolle.',
          'Im Null gibt es **keinen Trumpf**: Jeder Bube kehrt als ganz normale Karte in seine Farbe zurück. Auch die Reihenfolge ist wieder die „natürliche“: **A, K, D, B, 10, 9, 8, 7** – die Zehn rutscht unter den Buben.',
        ],
        rows: [{ label: 'Eine Farbe im Null, von hoch nach niedrig', cards: cards('S:A K Q J 10 9 8 7') }],
        tip: 'Nur Siebenen, Achten und Neunen auf der Hand? Nicht seufzen – das kann ein wunderschöner Null sein.',
      },
      ...times(2, () => orderDrill({ kind: 'null' })),
      ...times(2, () => trickWinnerDrill({ kind: 'null' })),
      {
        kind: 'play',
        prompt: 'Spiel: **Null**, du bist Alleinspieler. Ein Gegenspieler spielt ♣9 aus. Du hast drei Kreuzkarten – welche ist die beste?',
        contract: { kind: 'null' },
        hand: cards('C:Q 8 7 | H:7 8 | D:9'),
        trick: cards('C:9'),
        trickBy: ['Gegenspieler'],
        best: cards('C:8'),
        whyNot: 'Erlaubt, aber nicht die beste. Die ♣D liegt über der ♣9 – du könntest den Stich bekommen und sofort verlieren. Die ♣7 ist sicher, verschenkt aber die Gelegenheit, eine höhere Karte loszuwerden.',
        explain: 'Spiel **die höchste Karte, die noch unter dem Tisch liegt**: Die ♣8 entgeht dem Stich, und die ♣7 bleibt dir als Rettungskarte für später.',
      },
    ],
  },
  {
    id: '6',
    title: 'Was ein Spiel wert ist',
    promise: 'Den Wert jedes Blattes ausrechnen – die Grundlage für das ganze Reizen.',
    emoji: '🧮',
    minutes: 2,
    steps: [
      {
        kind: 'teach',
        title: 'Spielwert = Grundwert × Stufe',
        body: [
          'Jedes Spiel hat einen **Grundwert**, nach der Farbreihenfolge:',
          '**♦ Karo 9 · ♥ Herz 10 · ♠ Pik 11 · ♣ Kreuz 12 · Grand 24**',
          'Was das Spiel wirklich wert ist, ist der Grundwert mal einer **Stufe** (wie viel-fach es zählt). Woher kommt die Stufe? Zuerst von den Spitzen.',
        ],
        tip: 'Null wird nicht multipliziert – es hat feste Werte (ab 23), Thema in Lektion 9.',
      },
      {
        kind: 'teach',
        title: 'Spitzen: vom ♣B abwärts zählen',
        body: [
          'Leg die Trümpfe von hoch nach niedrig in eine Reihe: ♣B, ♠B, ♥B, ♦B, dann A, 10, K … der Trumpffarbe.',
          '**Du hast den ♣B** → zähl, wie viele Trümpfe du von ihm an **lückenlos** hast: Du spielst „**mit** so vielen“. ♣B ♠B, aber kein ♥B = mit 2.',
          '**Dir fehlt der ♣B** → zähl, wie viele Trümpfe dir von oben an **fehlen**: Du spielst „**ohne** so viele“. ♣B ♠B fehlen, ♥B hast du = ohne 2.',
          '„Mit“ und „ohne“ zählen genau gleich. Und beim Zählen **gehört der Skat zu den Karten des Alleinspielers**.',
        ],
        rows: [
          { label: 'Mit 2 (Lücke beim ♥B)', cards: cards('C:J | S:J | D:J | H:A') },
          { label: 'Ohne 2 (erst ab ♥B vorhanden)', cards: cards('H:J | D:J | H:A 10') },
        ],
      },
      {
        kind: 'teach',
        title: 'Stufe = Spitzen + 1 + Extras',
        body: [
          'Stufe = Anzahl der Spitzen, **+1** („Spiel“ – dafür, dass überhaupt gespielt wird), dazu mögliche Extras (Hand, Schneider … Lektionen 8 und 9).',
          'Beispiel: Du spielst Herz mit ♣B ♠B, aber ohne ♥B. Mit 2, Spiel 3. Herz hat den Grundwert 10 → **10 × 3 = 30**.',
          'Beispiel: Du spielst Kreuz ganz ohne Buben; dein höchster Trumpf ist das ♣A. Ohne 4, Spiel 5 → **12 × 5 = 60**.',
        ],
        tip: 'Am Tisch rechnet man genau so laut vor: „Mit zwei, Spiel drei, mal zehn: dreißig.“',
      },
      ...times(3, matadorDrill),
      ...times(3, gameValueDrill),
    ],
  },
  {
    id: '7',
    title: 'Reizen',
    promise: 'Das Tischgespräch „18?“ – „Ja.“ „20?“ – „Passe.“ verstehen und mitreden.',
    emoji: '📣',
    minutes: 2,
    steps: [
      {
        kind: 'teach',
        title: 'Was gereizt wird',
        body: [
          'Beim Reizen wird entschieden, wer Alleinspieler wird. Gereizt werden **Zahlen**, und jede heißt: „Das Spiel, das ich vorhabe, ist mindestens so viel wert.“ Wer sich am höchsten traut, wird Alleinspieler.',
          'Bevor du reizt, schau also in dein Blatt, überleg, was du spielen würdest, und rechne seinen Wert so aus wie in der letzten Lektion – **bis dahin darfst du reizen**.',
          'Der kleinste Reizwert ist **18** (Karo mit oder ohne 1: 9 × 2).',
        ],
      },
      {
        kind: 'teach',
        title: 'Die drei Plätze',
        body: [
          '**Vorhand**: links vom Geber. Vorhand spielt zum ersten Stich aus.',
          '**Mittelhand**: der nächste Spieler nach Vorhand.',
          '**Hinterhand**: der Geber selbst.',
          'Gereizt wird in zwei Duellen: **Zuerst reizt Mittelhand Vorhand**, bis einer aussteigt; **dann fordert Hinterhand den Sieger heraus**.',
        ],
      },
      {
        kind: 'teach',
        title: 'So läuft ein Duell',
        body: [
          'Einer **sagt** Zahlen, der andere **hört**. Wer sagt, nennt eine Zahl; wer hört, antwortet mit einem Wort: **„Ja“** (das würde ich auch spielen) oder **„Passe“** (ich steige aus).',
          'Mittelhand: „18?“ — Vorhand: „Ja.“',
          'Mittelhand: „20?“ — Vorhand: „Ja.“',
          'Mittelhand: „22?“ — Vorhand: „Passe.“ → Mittelhand gewinnt, gereizt ist bis 22.',
          'Dann reizt Hinterhand Mittelhand: „23?“ … bis einer passt. Wer übrig bleibt, ist Alleinspieler, und sein Spiel **muss mindestens so viel wert sein wie der letzte Reizwert**.',
        ],
        tip: 'Hören ist der bequemere Platz: Man muss nur mithalten, nicht überbieten. Mit denselben Karten wird deshalb Vorhand am ehesten Alleinspieler.',
      },
      {
        kind: 'teach',
        title: 'Die Reizwerte',
        body: [
          'Gereizt werden dürfen nur Zahlen, die ein Spiel wirklich wert sein kann:',
          '**18 · 20 · 22 · 23 · 24 · 27 · 30 · 33 · 35 · 36 · 40 · 44 · 45 · 46 · 48 · 50 …**',
          'Das sind die Vielfachen von 9, 10, 11, 12 und 24 (ab dem Zweifachen), dazu die vier festen Nullwerte 23, 35, 46, 59.',
          'Will niemand reizen (Vorhand nimmt nicht einmal 18), wird das Spiel **eingepasst** und neu gegeben.',
        ],
      },
      { kind: 'choice', prompt: 'Wer nennt beim Reizen die erste Zahl?', options: ['Vorhand', 'Mittelhand', 'Hinterhand', 'Wen der Geber bestimmt'], answer: 1, explain: 'Mittelhand reizt zuerst Vorhand, und Vorhand antwortet „Ja“ oder „Passe“. Hinterhand wartet auf den Sieger dieses Duells.' },
      { kind: 'choice', prompt: 'Welche Zahl darf nach „18“ als Nächstes gereizt werden?', options: ['19', '20', '21', '24'], answer: 1, explain: '20 = Herz 10 × 2. Kein Spiel ist 19 oder 21 wert, deshalb darf sie niemand reizen.' },
      { kind: 'choice', prompt: 'Zu welchem Spiel gehört die 23 bei den Reizwerten?', options: ['Karo × 2,5', 'Einem einfachen Null', 'Grand', 'Pik Hand'], answer: 1, explain: '23 ist der feste Wert des einfachen Null – absichtlich zwischen 22 und 24 gelegt, damit ein gutes Nullblatt das billigste Farbspiel überreizen kann.' },
      ...times(2, gameValueDrill),
      { kind: 'choice', prompt: 'Dein Blatt ist als Herzspiel 30 wert. Ein Gegner fragt dich: „33?“ Was antwortest du?', options: ['„Ja“ – nur nicht klein beigeben', '„Passe“', '„36!“ – ihn überbieten', 'Gar nichts sagen'], answer: 1, explain: 'Mit „Ja“ verpflichtest du dich zu einem Spiel, das mindestens 33 wert ist – deins ist 30 wert. Das ist **überreizt**: verloren, egal wie du spielst, und doppelt gezählt.', hint: 'Deine Grenze ist 30. Und 33 ist …' },
      {
        kind: 'teach',
        title: 'Welches Blatt lohnt das Reizen?',
        body: [
          'Grobe Faustregeln (im Schnitt verbessert der Skat dein Blatt um etwa eine Karte):',
          '**Farbspiel**: mindestens 5 Trümpfe (Buben mitgezählt), dazu ein oder zwei Asse in den Fehlfarben.',
          '**Grand**: mindestens zwei, drei Buben (am besten mit ♣B), dazu zwei, drei Asse.',
          '**Null**: in jeder Farbe eine 7 oder 8 ganz unten und keine einsamen hohen Karten.',
          'Passt nichts davon? Dann sag „Passe“ und spiel entspannt als Gegenspieler – gewinnen die Gegenspieler, hast du auch gewonnen.',
        ],
      },
    ],
  },
  {
    id: '8',
    title: 'Skat, Drücken und Hand',
    promise: 'Als Alleinspieler wissen, wie man die beiden Skatkarten am besten nutzt.',
    emoji: '🗃️',
    minutes: 2,
    steps: [
      {
        kind: 'teach',
        title: 'Das Vorrecht des Alleinspielers',
        body: [
          'Das Reizen gewonnen? Dann bist du Alleinspieler. Als Nächstes:',
          '**① Nimm den Skat auf** – jetzt hast du 12 Karten.',
          '**② Drück zwei Karten** verdeckt weg (die eben aufgenommenen oder beliebige andere).',
          '**③ Sag dein Spiel an.**',
          'Die zwei gedrückten Karten spielen nicht mit, aber ihre **Augen zählen für den Alleinspieler** – ein Guthaben, bevor die erste Karte fällt.',
        ],
      },
      {
        kind: 'teach',
        title: 'Welche zwei drücken? Drei Faustregeln',
        body: [
          '**Augen sichern**: Eine blanke Zehn ohne schützendes Ass wird leicht vom Ass eines Gegners gefangen. Drück sie, und die 10 Augen sind sicher.',
          '**Eine Farbe blank machen**: Drück alle Karten einer Fehlfarbe. Spielt ein Gegner diese Farbe später aus, kannst du stechen.',
          '**Keine Trümpfe und keine Asse drücken**: Mit ihnen gewinnst du deine Stiche.',
        ],
      },
      {
        kind: 'choice',
        prompt: 'Du bist Alleinspieler und willst **Herz ♥** spielen. Nach dem Aufnehmen des Skats hast du diese 12 Karten. Welche zwei drückst du am besten?',
        rows: [{ cards: cards('C:J | H:J A 10 K 9 | S:A 7 | C:10 | D:K 8 7') }],
        options: ['♣10 und ♦K', '♠A und ♠7', '♥9 und ♦7', '♦8 und ♦7'],
        answer: 0,
        explain: 'Die ♣10 steht blank: Sobald ein Gegner das ♣A spielt, verschenkt sie 10 Augen. Drück sie, und die 10 Augen sind dir sicher – außerdem bist du jetzt in Kreuz frei und kannst es später stechen. Mit dem ♦K kommen 4 dazu: schon 14 Augen im Skat.',
        hint: 'Welche Karte ist wertvoll, aber nicht zu halten? Welche Farbe ist nach einer gedrückten Karte leer?',
      },
      {
        kind: 'teach',
        title: 'Hand: ohne den Skat anzusehen',
        body: [
          'Dein Blatt ist schon gut genug? Dann kannst du **Hand** ansagen: Du **lässt den Skat liegen** und spielst mit den 10 Karten, die du bekommen hast. Die Belohnung: eine Stufe **mehr**.',
          'Der Skat gehört trotzdem dir: Nach dem Spiel zählen seine Augen für dich, und **beim Zählen der Spitzen wird er mitgerechnet**.',
          'Genau darin liegt das Risiko von Hand: Ein Bube im Skat kann deine Spitzen heimlich verändern.',
        ],
      },
      {
        kind: 'choice',
        prompt: 'Dein höchster Trumpf ist der ♥B (kein ♣B, kein ♠B), also spielst du Pik Hand „ohne 2“: 11 × (2 + 1 + 1) = 44, und du hast 44 gereizt. Nach dem Spiel wird der Skat umgedreht – darin liegt der **♣B**. Was jetzt?',
        options: ['Nichts ändert sich: weiter 44', 'Es wird „mit 1“: 11 × 3 = 33 – überreizt', 'Es wird „mit 3“ – mehr wert', 'Der Skat zählt nicht, also egal'],
        answer: 1,
        explain: 'Der Skat zählt zu den Karten des Alleinspielers. Mit dem ♣B spielst du „mit“, aber der ♠B gehört dir nicht, also nur „mit 1“: Stufe 1 + 1 + 1 = 3, Spielwert 33 < Reizwert 44 – **überreizt**, das Spiel ist verloren. Wer ein Handspiel „ohne“ spielt, lässt immer etwas Luft.',
        hint: 'Der ♣B gehört jetzt dir. Wie viele Trümpfe hast du vom ♣B an lückenlos?',
      },
      { kind: 'choice', prompt: 'Wem gehören im Handspiel am Ende die Augen der beiden ungesehenen Skatkarten?', options: ['Den Gegenspielern', 'Dem Alleinspieler', 'Wer den letzten Stich bekommt', 'Niemandem – sie zählen nicht'], answer: 1, explain: 'Der Skat gehört immer dem Alleinspieler, ob er ihn angesehen hat oder nicht.' },
    ],
  },
  {
    id: '9',
    title: 'Gewinnstufen und Abrechnung',
    promise: 'Ein fertiges Spiel selbst abrechnen – mit Schneider, Schwarz und überreizten Spielen.',
    emoji: '🏆',
    minutes: 2,
    steps: [
      {
        kind: 'teach',
        title: 'Schneider und Schwarz',
        body: [
          'Wer hoch gewinnt, bekommt mehr Stufen:',
          '**Schneider**: Die verlierende Seite hat **30 Augen oder weniger** (die Gewinner also ≥ 90). Eine Stufe **mehr**.',
          '**Schwarz**: Die verlierende Seite hat **keinen einzigen Stich** bekommen. **Noch** eine Stufe mehr.',
          'Vorsicht, das gilt in beide Richtungen: Ein Alleinspieler mit 30 Augen oder weniger zahlt den Schneider selbst – und das verlorene Spiel zählt dann doppelt.',
        ],
      },
      {
        kind: 'teach',
        title: 'Ansagen gibt es nur beim Handspiel',
        body: [
          'Wer Hand spielt, darf vor dem Spiel noch große Versprechen machen; jedes bringt eine Stufe **mehr**:',
          '**Schneider angesagt** – „Ich bekomme mindestens 90.“',
          '**Schwarz angesagt** – „Ich bekomme alle zehn Stiche.“',
          '**Ouvert** (offen) – „Ich lege meine Karten offen auf den Tisch und bekomme trotzdem alle zehn Stiche.“',
          'Wer ansagt und es nicht schafft – und sei es mit 89 –, hat verloren.',
        ],
      },
      {
        kind: 'teach',
        title: 'Die vier festen Nullwerte',
        body: ['Null kennt keine Spitzen, nur vier feste Werte:', '**Null 23 · Null Hand 35 · Null ouvert 46 · Null ouvert Hand 59**', 'Null ouvert heißt: Null mit offen aufgelegten Karten – nur für ein Blatt aus kleinen Karten, dem nichts passieren kann.'],
      },
      {
        kind: 'teach',
        title: 'Abrechnung',
        body: [
          '**Der Alleinspieler gewinnt**: + Spielwert.',
          '**Der Alleinspieler verliert**: − **2 ×** Spielwert. Ein verlorenes Spiel kostet doppelt so viel, wie ein gewonnenes bringt – also nicht leichtsinnig reizen.',
          '**Überreizt**: Das Spiel ist weniger wert als gereizt – verloren, egal wie viele Augen. Gewertet wird das kleinste Vielfache des Grundwerts, das den Reizwert erreicht, und zwar doppelt.',
          'Die Gegenspieler schreiben nichts Eigenes auf – das Ergebnis des Alleinspielers ist die ganze Abrechnung des Spiels. Nach mehreren Spielen gewinnt, wer die meisten Punkte hat.',
        ],
        tip: 'Bei offiziellen Turnieren bekommt der Alleinspieler zusätzlich +50 für jedes gewonnene und −50 für jedes verlorene Spiel, und die Gegenspieler bekommen Punkte dazu (Seeger-Fabian). Zu Hause lässt man das meist weg.',
      },
      ...times(4, settleDrill),
      { kind: 'choice', prompt: 'Was ist ein Null ouvert (Skat aufgenommen, offen gespielt) wert?', options: ['23', '35', '46', '59'], answer: 2, explain: '23 (einfach) → 35 (Hand) → **46 (ouvert)** → 59 (ouvert Hand).' },
      { kind: 'choice', prompt: 'Der Alleinspieler hat am Ende 89 Augen. Ist das Schneider?', options: ['Ja', 'Nein, dafür braucht es 90', 'Kommt darauf an, ob die Gegenspieler einen Stich haben', 'Nur beim Handspiel'], answer: 1, explain: 'Die Gegenspieler dürfen höchstens 30 haben, der Alleinspieler braucht also 90. 89 : 31 – knapp daneben.' },
    ],
  },
  {
    id: '10',
    title: 'Richtig spielen: Grundlagen für Alleinspieler und Gegenspieler',
    promise: 'Nicht mehr nur erlaubte Karten legen – sondern wissen, warum du genau diese spielst.',
    emoji: '🧠',
    minutes: 2,
    steps: [
      {
        kind: 'teach',
        title: 'Der Plan des Alleinspielers: erst Trumpf ziehen, dann kassieren',
        body: [
          'Wovor sich der Alleinspieler am meisten fürchtet: dass ein Gegner eines seiner Asse mit einem kleinen Trumpf sticht.',
          'Deshalb spielt der Alleinspieler meist zuerst **hohe Trümpfe hintereinander aus** und zwingt beide Gegner, Trumpf zu bedienen, bis sie keinen mehr haben (**Trumpf ziehen**). Es gibt 11 Trümpfe: Wie viele du hast und wie viele schon gefallen sind, verrät dir, wie viele die Gegner noch haben – **Trümpfe zählen** ist das erste Handwerk.',
          'Erst wenn die Gegner keine Trümpfe mehr haben, sind deine Asse und Zehnen in den Fehlfarben wirklich sichere Augen.',
        ],
      },
      {
        kind: 'play',
        prompt: 'Spiel: **Herz ♥**. Du bist Alleinspieler und spielst zum ersten Stich aus. Welche Karte?',
        contract: { kind: 'suit', trump: 'H' },
        hand: cards('C:J | S:J | H:A 10 9 | S:A 10 | C:7 | D:8 7'),
        trick: [],
        best: cards('C:J | S:J'),
        whyNot: 'Zu früh. Die Gegner haben noch 6 Trümpfe, und dein Ass kann leicht von einem kleinen Trumpf gestochen werden. Zieh erst mit deinen hohen Buben Trumpf.',
        explain: 'Den ♣B schlägt niemand, er gewinnt also sicher und holt zwei Trümpfe der Gegner heraus. Danach der ♠B, das ♥A … haben die Gegner keinen Trumpf mehr, sind ♠A und ♠10 geschenkte 21 Augen.',
      },
      {
        kind: 'teach',
        title: 'Der Plan der Gegenspieler: dem Partner schmieren',
        body: [
          'Die beiden Gegenspieler sind eine Seite, ihre Augen werden zusammengezählt. Ihr wichtigster Zug ist deshalb das **Schmieren**:',
          '**Dein Partner bekommt den Stich** → leg deine fetteste Karte dazu (ein Ass oder eine Zehn), damit der Stich mehr wert ist.',
          '**Der Alleinspieler bekommt den Stich** → wirf deine wertloseste Lusche ab und schenk ihm kein Auge.',
          'Außerdem: Gegenspieler **spielen nicht von sich aus Trumpf aus** – damit ziehen sie dem Alleinspieler die Trümpfe. Hast du ein Ass in einer Fehlfarbe, hol dir damit früh deinen Stich.',
        ],
      },
      {
        kind: 'play',
        prompt: 'Spiel: **Pik ♠**, du bist Gegenspieler. Dein Partner spielt ♦A aus, der Alleinspieler gibt ♦7 zu. Du bist dran – welche Karte?',
        contract: { kind: 'suit', trump: 'S' },
        hand: cards('D:10 8 | H:K 9 | C:Q'),
        trick: cards('D:A 7'),
        trickBy: ['Partner', 'Alleinspieler'],
        best: cards('D:10'),
        whyNot: 'Erlaubt, aber eine verpasste Gelegenheit. Das ♦A deines Partners hat den Stich schon sicher – jetzt ist der Moment, deine fetteste Karte dazuzulegen.',
        explain: 'Schmieren! ♦A + ♦7 + ♦10 = 21 Augen, alle für eure Seite. Mit der ♦8 wären es nur 11.',
      },
      {
        kind: 'play',
        prompt: 'Spiel: **Kreuz ♣**, du bist Gegenspieler. Der Alleinspieler spielt ♣B aus, dein Partner gibt ♣9 zu. Du musst Trumpf bedienen – mit welcher Karte?',
        contract: { kind: 'suit', trump: 'C' },
        hand: cards('C:10 8 | D:A | H:7'),
        trick: cards('C:J 9'),
        trickBy: ['Alleinspieler', 'Partner'],
        best: cards('C:8'),
        whyNot: 'Der ♣B ist die höchste Karte im Spiel: Den Stich hat der Alleinspieler sicher. Mit der ♣10 schenkst du ihm 10 Augen.',
        explain: 'Wenn du nicht gewinnen kannst, spiel klein. Heb die ♣10 auf – vielleicht holt sie später noch einen Stich.',
      },
      {
        kind: 'play',
        prompt: 'Spiel: **Herz ♥**. Du bist Alleinspieler und sitzt hinten. Die Gegenspieler haben ♠10 und ♠A gelegt, und du hast kein Pik. Welche Karte?',
        contract: { kind: 'suit', trump: 'H' },
        hand: cards('H:J 7 | D:K 9 | C:8'),
        trick: cards('S:10 A'),
        trickBy: ['Gegenspieler', 'Gegenspieler'],
        best: cards('H:7'),
        whyNot: 'Auf dem Tisch liegen 21 Augen – die musst du holen! Und weil du hinten sitzt, kann dich danach niemand mehr überstechen: Dein kleinster Trumpf reicht. Heb die großen auf.',
        explain: 'Wer hinten sitzt, gewinnt mit der kleinsten Karte, die gerade reicht. Die ♥7 holt 21 Augen, und der ♥B bleibt dir für später.',
      },
      { kind: 'choice', prompt: 'Herzspiel, du bist Alleinspieler mit 6 Trümpfen. Bisher sind 3 Trümpfe gefallen, 2 davon von den Gegnern. Wie viele Trümpfe haben die Gegner noch?', options: ['2', '3', '4', '5'], answer: 1, explain: 'Es gibt 11 Trümpfe. Du hast 6, die Gegner also zu Beginn 5; 2 haben sie gespielt, also bleiben **3**.', hint: '11 Trümpfe − deine 6 = wie viele hatten die Gegner am Anfang?' },
      { kind: 'choice', prompt: 'Was sollte ein Gegenspieler normalerweise **nicht** von sich aus ausspielen?', options: ['Ein Ass einer Fehlfarbe', 'Trumpf', 'Eine kleine Karte einer kurzen Farbe', 'Eine Farbe, die der Partner gezeigt hat'], answer: 1, explain: 'Wer Trumpf ausspielt, zieht dem Alleinspieler die Trümpfe. Die Trümpfe der Gegenspieler sind dafür da, Asse und Zehnen des Alleinspielers zu stechen.' },
    ],
  },
  {
    id: '11',
    title: 'Abschlussspiel: an den Tisch!',
    promise: 'Eine komplette Partie gegen zwei Computergegner spielen. Danach kannst du Skat.',
    emoji: '🎓',
    minutes: 3,
    steps: [
      {
        kind: 'teach',
        title: 'Spickzettel für den Tisch',
        body: [
          '**Augen** A 11 · 10 10 · K 4 · D 3 · B 2 | der Alleinspieler braucht **61**',
          '**Trümpfe** ♣B ♠B ♥B ♦B, dann die Trumpffarbe A 10 K D 9 8 7',
          '**Bedienen** Farbe bedienen, wenn du kannst; ein Bube ist Trumpf, nicht die Farbe, die auf ihm steht',
          '**Grundwerte** ♦9 ♥10 ♠11 ♣12 Grand 24 | Null 23/35/46/59',
          '**Spielwert** Grundwert × (Spitzen + 1 + Extras)',
          '**Reizen** Mittelhand → Vorhand, Hinterhand → Sieger; nur bis zum eigenen Spielwert reizen',
        ],
        tip: 'Im Spiel kannst du jederzeit auf „Tipp“ tippen: Er sagt dir, welche Karte du spielen sollst und warum. Keine Angst vorm Verlieren – aus einem verlorenen Spiel lernst du mehr als aus einem gewonnenen.',
      },
      {
        kind: 'game',
        title: 'Eine ganze Partie',
        body: ['Reizen, Skat, Ansagen, zehn Stiche, Abrechnung – einmal alles durch. Ob gewonnen oder verloren: Danach hast du den Kurs geschafft.'],
      },
    ],
  },
]
