/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/parrottoonTheme.ts
 * Command: astryx theme build src/theme/parrottoonTheme.ts --out src/theme/parrottoon.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const parrottoonIconRegistry: IconRegistry;
export declare const parrottoonTheme: DefinedTheme;
