/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as DailyPlayRouteImport } from './routes/daily_.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPlayRoute = DailyPlayRouteImport.update({
  id: '/daily_/play',
  path: '/daily/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/play': typeof PlayRoute
  '/rules': typeof RulesRoute
  '/course/$slug': typeof CourseSlugRoute
  '/daily/play': typeof DailyPlayRoute
  '/course/': typeof CourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/play': typeof PlayRoute
  '/rules': typeof RulesRoute
  '/course/$slug': typeof CourseSlugRoute
  '/daily/play': typeof DailyPlayRoute
  '/course': typeof CourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/play': typeof PlayRoute
  '/rules': typeof RulesRoute
  '/course/$slug': typeof CourseSlugRoute
  '/daily_/play': typeof DailyPlayRoute
  '/course/': typeof CourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily'
    | '/play'
    | '/rules'
    | '/course/$slug'
    | '/daily/play'
    | '/course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/play'
    | '/rules'
    | '/course/$slug'
    | '/daily/play'
    | '/course'
  id:
    | '__root__'
    | '/'
    | '/daily'
    | '/play'
    | '/rules'
    | '/course/$slug'
    | '/daily_/play'
    | '/course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  PlayRoute: typeof PlayRoute
  RulesRoute: typeof RulesRoute
  CourseSlugRoute: typeof CourseSlugRoute
  DailyPlayRoute: typeof DailyPlayRoute
  CourseIndexRoute: typeof CourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily_/play': {
      id: '/daily_/play'
      path: '/daily/play'
      fullPath: '/daily/play'
      preLoaderRoute: typeof DailyPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  PlayRoute: PlayRoute,
  RulesRoute: RulesRoute,
  CourseSlugRoute: CourseSlugRoute,
  DailyPlayRoute: DailyPlayRoute,
  CourseIndexRoute: CourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
