import { parrottoonTheme } from '~/theme/parrottoon'
import type { DefinedTheme } from '@astryxdesign/core/theme'

// ────────────────────────────────────────────────────────────────────────────
// THE THEME SWITCH — this file is the ONLY place Parrottoon names a theme.
//
// The theme itself is now **source in this repo**, not a package:
//
//   src/theme/parrottoonTheme.ts   the definition — palette, scales, typefaces,
//                                  component overrides. THIS is what you edit.
//   src/theme/parrottoon.{css,js}  generated by `astryx theme build`. Never
//                                  hand-edit; rebuild instead:
//
//   npx astryx theme build src/theme/parrottoonTheme.ts \
//     --out src/theme/parrottoon.css --icons-specifier ./icons
//
// It was scaffolded from Astryx's Matcha with `astryx theme add matcha`, which is
// the documented way to take ownership of a theme rather than patching
// node_modules. Owning it is what makes the palette change — which the human has
// said is coming — a one-file edit instead of a swap to somebody else's taste.
//
// To adopt a different OFFICIAL theme wholesale instead:
//   1. npx astryx theme add <slug> src/theme   (see `npx astryx theme list`)
//   2. point the import above at it, and set APP_THEME_NAME to its name
//   3. swap the @import in src/styles/app.css
//   4. swap the Google-Fonts link in routes/__root.tsx to that theme's typefaces
//
// See .intentfold/charter/ui.md § Guidance, "Switching the theme". Do NOT
// hard-code colours anywhere else — every product style references a token.
// ────────────────────────────────────────────────────────────────────────────
export const appTheme: DefinedTheme = parrottoonTheme

// Must equal appTheme.name. It is what `<Theme>` writes into `data-astryx-theme`,
// and what the SSR shell writes on <html> so the @scope'd theme CSS applies on the
// very first paint (no flash of unthemed content).
export const APP_THEME_NAME = 'parrottoon'

// Astryx supports 'light' | 'dark' | 'system'. Parrottoon is a daylight reading
// product and pins light rather than following the OS. Every token already carries
// its dark value, so 'system' is a one-word change if that is wanted.
export const APP_THEME_MODE = 'light' as const
