"""Writes the playing cards' corner-index glyphs (SKATGO-66) as SVG path data, from Bebas Neue (SIL Open
Font License, the product's numeral font). The index is drawn as paths, never text: SVG text is page text,
and a search engine would read the cards' letters into the page (SKATGO-29).

    python3 app/scripts/extract-card-glyphs.py BebasNeue-Regular.ttf > app/src/components/skat/card-glyphs.ts

Needs fontTools (not a dependency of the app; run it from any environment that has it). The font comes
from github.com/google/fonts, ofl/bebasneue/BebasNeue-Regular.ttf.
"""

import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

CHARS = '0123456789ABDJKOQU'

font = TTFont(sys.argv[1])
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
cap = font['OS/2'].sCapHeight
out = []
for ch in CHARS:
    name = cmap[ord(ch)]
    pen = SVGPathPen(glyphs, lambda v: f'{v:g}')
    # Font units, y down, the cap height's top at 0 and the baseline at `cap`.
    glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, 0, cap)))
    out.append(f"  '{ch}': {{ w: {glyphs[name].width}, d: '{pen.getCommands()}' }},")

print('// Generated by app/scripts/extract-card-glyphs.py from Bebas Neue (SIL Open Font License). Do not edit.')
print('// The playing cards\' corner-index glyphs (SKATGO-66) in font units: y runs down from the cap height\'s')
print('// top (0) to the baseline (CAP); `w` is the advance width.')
print(f'export const CAP = {cap}')
print('export const GLYPHS: Record<string, { w: number; d: string }> = {')
print('\n'.join(out))
print('}')
